### PR TITLE
Fix deprecations

### PR DESCRIPTION
**Pull request by SoTeKie**

### CODE REVIEW

**Comment by aosasona** [comment]
Hiya! Thanks a lot for this PR. 

Tests are currently failing and I believe there are a few other deprecations in there to fix. I am currently busy with work and cannot get to it at this moment but I will get to it and sort it out before the week ends.

**Comment by SoTeKie** [comment]
Hi! Sorry for missing the failed tests, I'll take a quick look, as for deprecations though you should be good, it looks like drop_right was the only one there

**Comment by aosasona** [comment]
Replaced by #14

**Comment by aosasona** [comment]
@SoTeKie Again, thank you very much for this PR! I have gone ahead to fix the other deprecations on a separate branch and tests are passing now, it appears the `os` env methods were also removed from the `gleam/erlang` package in a recent release.

**Comment by SoTeKie** [comment]
Nice! Sorry that I didn't catch the tests before pushing, I'm checking for deprecations on multiple packages and this one ended up falling through the cracks. Not sure why `gleam check` didn't report the env method missing though 🤔

**Comment by aosasona** [comment]
`gleam check` didn't show it here the first few times for some reason too. I decided to upgrade all the deps anyway, looks like the standard lib itself has quite a number of deprecations on the minimum version. No worries, thanks once again! I haven't written Gleam in almost a year now, so I wouldn't have caught it myself but happy to receive and merge contributions!

**Pull request closed without merging**
